### ISSUE TITLE
Disable audio and video in startup

### ISSUE THREAD

**Issue by maximzon** [jangouts/jangouts#222] opened 2018-04-18 17:02 UTC
I've installed Janus on Ubuntu OS.
How can i disable audio and video on startup to decrease a bandwidth? 
Most of the time in the audio there are indiscriminate sounds, how can it be fixed ?
Often the audio channel of some users is disconnected. Ignore and unignore is the workaround but with 10+ users that makes it impossible to follow the discussion.

**Comment by ancorgs** [comment] 2023-03-03 15:15
Kind of a duplicate of #80. Closing this in favor of the other.

**Closed by ancorgs** 2023-03-03 15:15 UTC
