### ISSUE TITLE
Focusing own video if speaking

### ISSUE THREAD

**Issue by manno** [jangouts/jangouts#162] opened 2016-11-08 15:21 UTC
I find it very confusing to get focused while speaking, but maybe this is by design. I like that the main video follows the speaker, but I'd suggest excluding the viewers own stream.

**Comment by ancorgs** [comment] 2016-12-27 12:36
It's by design. We used to use Google Hangouts and we disliked the fact that your stream is treated in a different way than the others. We usually have turn-based meetings with quite some people. And in Google Hangouts the following things were kind of weird (to us).

1) While you speak, everybody sees you as the main feed... everybody but you, who still see the guy that spoke before you (who maybe is now just picking his nose, I mean, he is not the starring anymore).

2) Since you are always the last in the list of participants, the list is not the same for everybody. So if you want to simply speak by turns you have to use "tricks" (for example, when you stop talking you announce who's next, based in YOUR list order).

With Jangouts we wanted to follow the approach of "everybody sees the very same".

I admit that's weird in 1:1 meetings, in which the other participant should always be in the focus... but that's only one click away.

I'm closing this because I don't want to fix it in isolation. I'd rather take it into account in a bigger redesign. For that, see https://groups.google.com/d/msg/jangouts/VpDoHYE0HL4/wZ43QITgAgAJ

**Closed by ancorgs** 2016-12-27 12:36 UTC

**Comment by bmwiedemann** [comment] 2016-12-30 19:37
IMHO, some global config options (stored in cookies) could help here. e.g. a "show myself in fullscreen while speaking" checkbox being default on
