### ISSUE TITLE
Jangouts not started

### ISSUE THREAD

**Issue by sunnybear** [jangouts/jangouts#220] opened 2018-04-14 08:12 UTC
dist/index.html gives only terracote screen (without elements, just black screen) and the following errors in console

app-20107677.js:7 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ app-20107677.js:7
(index):2 Uncaught SyntaxError: Unexpected token w in JSON at position 19
    at JSON.parse (<anonymous>)
    at app-20107677.js:7
    at Object.i [as invoke] (vendor-5fc96752.js:32)
    at vendor-5fc96752.js:32
    at o (vendor-5fc96752.js:32)
    at tn (vendor-5fc96752.js:32)
    at s (vendor-5fc96752.js:32)
    at at (vendor-5fc96752.js:32)
    at ot (vendor-5fc96752.js:32)
    at HTMLDocument.<anonymous> (vendor-5fc96752.js:36)

**Comment by imobachgs** [comment] 2020-02-17 20:57
Could it be that the `config.json` contains invalid data? Is this still an issue? (sorry for taking so much time to answer).

**Comment by ancorgs** [comment] 2020-04-29 07:40
Sorry for overlooking this initially. The issue is so old that I doubt it is still relevant. I'm closing it, but feel free to reopen if it still can be reproduced with recent versions.

**Closed by ancorgs** 2020-04-29 07:40 UTC
