### ISSUE TITLE
Can't see or send messages to other people in the same room

### ISSUE THREAD

**Issue by markkp** [jangouts/jangouts#174] opened 2017-01-30 19:54 UTC
In testing with Firefox 45.6.0 and 50.1.0, I'm not having any luck with jangouts.suse.de.  I can sign in, but I don't see my other signin session (with another name), so nothing typed into the message box is being shown to the other session.
I don't know if this has any bearing on the problem, but I'm doing my testing from KVM virtual machines, since my current laptop is not in the best of shape.

**Comment by ancorgs** [comment] 2017-02-02 12:03
I have never tried connecting from a KVM virtual machine. I will test if that's possible at all. In order to connect to Jangouts you need to have a microphone and, if possible, a camera. I guess you are sharing the host hardware devices (I have never tried).

**Comment by markkp** [comment] 2017-02-02 22:17
It appears that this is a duplicate of "Possibility to silently join and monitor rooms" #158. If I allow the sharing of the audio device, then all participants can see me, and what ever I type in the messages area. So while #158 is marked as an enhancement request, it appears to actually be a bug.

**Comment by ancorgs** [comment] 2017-02-03 07:01
Not exactly, as I see it.

You are hitting a real bug that is preventing you to get fully joined to a room and makes your connection one-direction (send but not receive), even if you want to get fully connected. This issue is here to debug that.

#158 is about enhancing the UI, so people that is in the room but only in one direction (listening but not sending or the other way around) is noticed by the other participants. One-direction connections are (and will be) always possible due to Janus design, not only due to your concrete technical problem, but also by any other one or even intentionally.

**Comment by ancorgs** [comment] 2023-03-03 15:03
Issues marked as "related_to_vpn" seemed to only happen in the SUSE VPN. We have never been able to reproduce them in VPN-free environments.

So I'm closing them all.

If you believe it's a general problem non related to VPN, please verify it at https://li2023-182.members.linode.com/

**Closed by ancorgs** 2023-03-03 15:03 UTC
Labels: bug, Related_to_VPN
