### ISSUE TITLE
Other people can not see or hear me (allowed audio/video)

### ISSUE THREAD

**Issue by okurz** [jangouts/jangouts#184] opened 2017-03-16 09:28 UTC
## observation

This is similar to #158 but not intentional and sporadic. Even if audio/video devices are present and allowed to be shared it can happen sometimes that after joining a room other people can not see or hear one person. There is no indication whatsoever that the person is hearing or seeing other people also not for the person in question. In most cases a reload of the webpage (or "reconnect") can fix this.

On a testing machine with SLES 12 SP3 (current development) build with Firefox 45.7.0 installed the issue appears reproducibly (CPU Intel Core 2 Duo U7600 1.20GHz).

The issue is annoying because in most cases it is not obvious to the person in question that no one can hear him.

## workaround

Reconnect to room (or try different browser).

**Comment by code-master5** [comment] 2017-03-16 16:56
@okurz Hey there! I also faced similar problems while I was trying to run Jangouts on my localhost for first few times. Infact I also discussed this with @ancorgs and @imobachgs . Finally I was able to figure out, thanks to them. May be my experience with this can help. 
The problem was that in both firefox and chrome, I could not connect with any of the participants in the room. Then I figured out that in Janus config file at `src/config.json`, if the http url for `janusServer` property is defined, then browser tries to connect to janus with this url. As you can notice, this url is not SSL. In modern browsers SSL is becoming more of a hard requirement. Then I just added https url for `janusServerSSL` property in the config file. The problem was still there. But this time, I noticed that in firefox, sometimes reloading could fix this and sometimes not. For chrome, I still could not connect with anyone at all. This may be happened because the firefox after reloading might be trying to connect using SSL url. Then I tried a workaround. I set `janusServer` property to null and kept only the `janusServerSSL` url. Now browser had no option but to connect using SSL. Since then, I am using and testing Jangouts everyday, sometimes with as much as 10 - 11 particpants. None of the participants faced this problem ever again.

**Comment by ancorgs** [comment] 2017-03-17 12:13
@okurz the problem mentioned by @code-master5 should not happen in our internal instance, since all traffic should be enforced to use SSL. But since "should" is the key word here, @code-master5's solution is worth a try. I updated the configuration setting `janusServer` to null. So please, go to https://jangouts.suse.de/config.json and reload to ensure you see `"janusServer": null` there.

Then, once we are sure you don't have the old configuration cached, reload https://jangouts.suse.de and try if it works better now.

**Comment by okurz** [comment] 2017-03-17 14:08
thank you. I tried here, confirmed the configuration after forced reload but the system I was originally reporting about still shows up as invisible consistently. What we found out though is that from the main page showing the room list the room shows all attendees, including the invisible one. When joining the room the invisible one does not show up.

**Comment by code-master5** [comment] 2017-03-17 14:18
@okurz That's exactly what happened in my case too. Also, the invisible member was not able to recieve any chat messages.

**Comment by ancorgs** [comment] 2017-03-17 15:25
As commented in other issue reports, mail threads and even Hack Week project, the invisible participants are just a symptom of another problem. And that problem can be anything preventing the three WebRTC channels to be connected. The root problem can be even completely different for two "stealth participants" in the same call.

We are cooking a GSoC idea to integrate Jangouts with https://www.callstats.io (as a joint effort with CallStats developers). That would make easier to debug the exact cause of every failure.

**Comment by pevik** [comment] 2020-02-11 12:35
@imobachgs @dgdavid thank you for working on other issues recently.
FYI we stopped to use jangouts due functional problems like this one (and migrate to gotomeeting). It'd be nice to have this (and issues like #221) fixed.

**Comment by ancorgs** [comment] 2023-03-03 15:01
Issues marked as "related_to_vpn" seemed to only happen in the SUSE VPN. We have never been able to reproduce them in VPN-free environments.

So I'm closing them all.

If you believe it's a general problem non related to VPN, please verify it at https://li2023-182.members.linode.com/

**Closed by ancorgs** 2023-03-03 15:01 UTC
Labels: Related_to_VPN
