### ISSUE TITLE
Detection of disconnects

### ISSUE THREAD

**Issue by manno** [jangouts/jangouts#161] opened 2016-11-08 15:19 UTC
Sometimes the application does not detect a disconnect. Neither the disconnected client, nor the other participants get notified.
The client keeps showing the old images. If people were not moving much, it's hard to understand they're offline and not very, very still.

Better handling of disconnects would be great, but it might be beneficial to add a 'network health' icon, like a traffic light, to every participant.

**Comment by ancorgs** [comment] 2016-12-27 13:11
That has never happened to us. I would need detailed instructions to reproduce it.

**Comment by anweshknayak** [comment] 2017-01-09 18:28
@manno @ancorgs anyone working on it ?

**Comment by ancorgs** [comment] 2017-01-10 06:31
As said in my previous comment, I cannot fix it since I have never observed it. I would need a more or less reliable way of reproducing it.

**Comment by anweshknayak** [comment] 2017-01-10 08:52
@ancorgs any other issue I can work on ?

**Comment by ancorgs** [comment] 2017-01-25 17:19
@anweshknayak Sure, just for you I have just created the "[junior job](https://github.com/jangouts/jangouts/issues?q=is%3Aissue+is%3Aopen+label%3A%22junior+job%22)" label. Enjoy

**Comment by ancorgs** [comment] 2023-03-03 15:00
Issues marked as "related_to_vpn" seemed to only happen in the SUSE VPN. We have never been able to reproduce them in VPN-free environments.

So I'm closing them all.

If you believe it's a general problem non related to VPN, please verify it at https://li2023-182.members.linode.com/

**Closed by ancorgs** 2023-03-03 15:00 UTC
Labels: Related_to_VPN
