### ISSUE TITLE
Do not get remote videos after asking for permissions

### ISSUE THREAD

**Issue by imobachgs** [jangouts/jangouts#387] opened 2022-07-01 09:53 UTC
It looks like Jangouts does not display remote videos after asking for mic/camera permissions. However, if it does not need to ask for those permissions, it works just fine.

**Comment by ancorgs** [comment] 2023-02-01 14:39
I cannot reproduce this in my development environment.

**Comment by ancorgs** [comment] 2023-02-03 13:07
We did a debugging session and looks like nobody reproduced this. I'm going to close it for now. We may re-open it if you observe that happening again.

**Comment by ancorgs** [comment] 2023-02-11 09:55
Closing as WORKSFORME as commented.

**Closed by ancorgs** 2023-02-11 09:55 UTC
Labels: bug, react, help wanted
